"""Update GPS_data table structure

Revision ID: 4f84e5c8808a
Revises: f950fc747eb3
Create Date: 2025-09-06 17:00:54.296055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f84e5c8808a'
down_revision: Union[str, Sequence[str], None] = 'f950fc747eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Latitude', sa.Float(), nullable=False),
    sa.Column('Longitude', sa.Float(), nullable=False),
    sa.Column('Altitude', sa.Float(), nullable=False),
    sa.Column('Accuracy', sa.Float(), nullable=False),
    sa.Column('Timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gps_data')
    # ### end Alembic commands ###
